  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.living_room
      - group.bedroom
      - group.media
      - weather.weather
      - device_tracker.iphone
      - sensor.home_humid
      - sensor.home_temp
  living_room:
    name: Living Room
    entities:
      - switch.living_room_light
      - switch.ac_switch
  bedroom:
    name: Master Bedroom
    entities:
      - switch.master_bedroom_fan
      - switch.master_bedroom_light
  system:
    name: System Monitor
    control: hidden
    view: yes
    entities:
      - group.hardware
      - group.docker
      - media_player.plex
  hardware:
    name: Hardware Monitor
    control: hidden
    entities:
      - sensor.cpu_temperature
      - sensor.disk_use_percent_home
      - sensor.memory_free
      - sensor.raid_status
  docker:
    name: Docker Containers
    entities:
      - switch.headphones
      - switch.home_assistant
      - switch.jackett
      - switch.radarr
      - switch.sonarr
      - switch.lazy_librarian
      - switch.nextcloud
      - switch.nextcloud_db
      - switch.mosquitto
      - switch.plex_media_server
      - switch.transmission
  media:
    name: Media
    view: yes
    entities:
      - group.applications
      - group.sonarr
      - group.radarr
      - group.transmission
  sonarr:
    name: Sonarr (TV Series)
    entities:
      - sensor.sonarr_upcoming
      - sensor.sonarr_queue
      - sensor.sonarr_series
      - sensor.sonarr_wanted
  radarr:
    name: Radarr (Movies)
    entities:
      - sensor.radarr_movies
      - sensor.sonarr_upcoming
  transmission:
    name: Transmission (Downloads)
    entities:
      - sensor.transmission_active_torrents
      - sensor.transmission_down_speed
      - sensor.transmission_paused_torrents
      - sensor.transmission_status
      - sensor.transmission_total_torrents
      - sensor.transmission_up_speed
  applications:
    name: Applications
    entities:
      - weblink.plex_media_server
      - weblink.radarr_add_movies
      - weblink.sonarr_add_tv_series
      - weblink.headphones_add_music
      - weblink.lazy_librarian_add_ebooks
      - weblink.nextcloud
      - weblink.transmission_downloads
      - weblink.jackett_indexers
