
c83a6ba3be52:
  hide_if_away: false
  icon:
  mac: C8:3A:6B:A3:BE:52
  name: c83a6ba3be52
  picture:
  track: false

davidsipodtouch:
  hide_if_away: false
  icon:
  mac: 00:88:65:05:0C:8C
  name: DavidsiPodtouch
  picture:
  track: false

hs110:
  hide_if_away: false
  icon:
  mac: 50:C7:BF:7C:FD:F7
  name: HS110
  picture:
  track: false

aaronhpprobook6460b:
  hide_if_away: false
  icon:
  mac: 20:10:7A:3E:06:BB
  name: aaron-HP-ProBook-6460b
  picture:
  track: false

iphone:
  hide_if_away: false
  icon:
  mac: 8C:8E:F2:93:F3:48
  name: Aaron
#  picture: https://www.home-assistant.io/images/favicon-192x192.png
  picture: /local/logo2.png
  track: true

ahumphrieslt:
  hide_if_away: false
  icon:
  mac: 10:02:B5:D7:E3:9E
  name: AHUMPHRIES-LT
  picture:
  track: false

amazonf2dbb82bb:
  hide_if_away: false
  icon:
  mac: FC:65:DE:72:A6:33
  name: amazon-f2dbb82bb
  picture:
  track: false

00015c67b246:
  hide_if_away: false
  icon:
  mac: 00:01:5C:67:B2:46
  name: 00015c67b246
  picture:
  track: false

ubuntuserver02:
  hide_if_away: false
  icon:
  mac: 6C:F0:49:07:11:79
  name: ubuntuserver02
  picture:
  track: false

0024e818e40a:
  hide_if_away: false
  icon:
  mac: 00:24:E8:18:E4:0A
  name: 0024e818e40a
  picture:
  track: false

hs110_2:
  hide_if_away: false
  icon:
  mac: 50:C7:BF:7C:EF:7D
  name: HS110
  picture:
  track: false

hs200:
  hide_if_away: false
  icon:
  mac: AC:84:C6:97:A6:F9
  name: HS200
  picture:
  track: false

ac84c6979d65:
  hide_if_away: false
  icon:
  mac: AC:84:C6:97:9D:65
  name: ac84c6979d65
  picture:
  track: false
